### ISSUE TITLE
Money rewards not changing players balance

### ISSUE THREAD

**Issue by FortyEffs** [BentoBoxWorld/addon-challenges#10]
Money rewards aren't working. No console errors. Using vault and essentials.

**Comment by tastybento** [comment]
Yes, actually money is not currently supported. It still need to be added.

**Comment by tastybento** [comment]
As a work around, you can use reward commands to pay the player.

**Comment by FortyEffs** [comment]
Yeah I didn't know what the timeline might be for adding that. I'll go ahead and use commands then.
