### ISSUE TITLE
Expert challenges command issue

### ISSUE THREAD

**Issue by BarnabyD** [BentoBoxWorld/addon-challenges#11]
When running **/island challenges**, clicking on the Expert book just closes the GUI (and shows a null error in console). It appears to be running **/island challenges Expert**

I can manually run **/is challenges expert** (lower case), and it opens fine.

Error log: [https://pastebin.com/E4wr8ku3](https://pastebin.com/E4wr8ku3)

**Comment by tastybento** [comment]
Yes, I can replicate this. I'll track down why that's happening. It should be case insensitive.

**Comment by tastybento** [comment]
Thanks for the report. This was actually a bug in BentoBox's panel API that I just fixed with the last commit there. https://github.com/BentoBoxWorld/bentobox/commit/4eadd259f7179df143a5bb69fb53cf5370c7a065
