### ISSUE TITLE
BSB challenges

### ISSUE THREAD

**Issue by tastybento** [BentoBoxWorld/addon-challenges#12]
_From @SlimeDog on September 1, 2018 0:55_

Spigot 1.13 latest
BB/BSB 0.9.0-alpha1

I have started testing the new challenges. Based on what is available in the single island schematic (compared with three in ASB), I do not see how some of the novice challenges can be met.

- beetroot seeds :: Beetroot seeds are available only in Village garden plots (as beets) or in EndCity chests. Neither beets nor beetroot seeds are available in the island inventory or on the island itself, or as reward for any novice challenge.
- cactus green dye :: Cactus green available only in Igloo chests or by processing cactus. Cacti grow naturally only in Desert and Badlands biomes; the island is a Plains biome. Igloos are not available in the Plains biome.
- paper :: Paper is available only in Shipwreck or Stronghold chests, or by processing sugarcane. With the two sand blocks available after converting one to glass (another challenge), it might be possible to generate a natural sugarcane. Otherwise, sugarcane is not available in the island inventory.

Am I missing something?

_Copied from original issue: BentoBoxWorld/bentobox#254_

**Comment by tastybento** [comment]
@SlimeDog - fixed in latest commit. Thanks!

**Comment by SlimeDog** [comment]
Confirmed fixed in latest island.schem. It includes a cow and additional chest contents: beetroot, cactus, and sugarcane.

**Comment by SlimeDog** [comment]
Unfortunately, the required material is not _beetroot_, but _beetroot seeds_. Also, we need _pumpkin_, rather than _carved_pumpkin_, in order to obtain _pumpkin seeds_.
