### ISSUE TITLE
Cannot do challenge, when added to island

### ISSUE THREAD

**Issue by Kryniowesegryderiusz** [BentoBoxWorld/addon-challenges#19]
People added to island by /is team invite cant do challenges with type island :/
It could be connected with problems described [here](https://github.com/BentoBoxWorld/bentobox/issues/297) with adding players to islands

**Comment by Kryniowesegryderiusz** [comment]
Sometimes there is also problem with owner - it tells him that he have to do it on his island. But it already is his island.

**Comment by tastybento** [comment]
Sorry for late reply. Is this still an issue?

**Comment by Kryniowesegryderiusz** [comment]
No, it's not
