### ISSUE TITLE
duplication in locale file?

### ISSUE THREAD

**Issue by DuckSoft** [BentoBoxWorld/addon-challenges#2]
https://github.com/tastybento/addon-challenges/blob/c3c51b957c6ad7ee1bd9eeb1fafe9b6eea65e6ad/locales/en-US.yml#L11
https://github.com/tastybento/addon-challenges/blob/c3c51b957c6ad7ee1bd9eeb1fafe9b6eea65e6ad/locales/en-US.yml#L24

**Comment by tastybento** [comment]
Yup. Thanks.
