### ISSUE TITLE
Money rewards

### ISSUE THREAD

**Issue by Bobbbe** [BentoBoxWorld/addon-challenges#25]
**Description**
- "Economy" I do not receive any rewards for the "challenges" completed and we do not receive the amount of money to be received from a new island that is configured at $ 10 in the config file of bentobox.

Maybe "essentials economy" is not considered an economy plugin or is not recognized.

**Server Information:**

[Please complete the following information:]
 - Database being used (Flat file, MySQL, Mongo): yaml
 - OS: [e.g. iOS] Omgserv bungeecord spigot 1.13.2
 - Java Version:  Java 8
 - BentoBox version: Alpha 7. 0.14.0-snapshot
 - Addons installed? 
[BentoBox] Loaded 6 addons.
[Server thread/INFO]: [BentoBox] Enabling addons...
[Server thread/INFO]: [BentoBox] Enabling BSkyBlock...-0.5.0-snapshot
[Server thread/INFO]: [BentoBox] Enabling AcidIsland...-0.4.1-snapshot
[Server thread/INFO]: [BentoBox] Enabling BentoBox-InvSwitcher...-0.0.1-snapshot
[Server thread/INFO]: [BentoBox] Loading challenges...-
[Server thread/INFO]: [BentoBox] Enabling BentoBox-Challenges...-0.03-snapshot
[Server thread/INFO]: [BentoBox] Enabling Level...-0.1.0-snapshot
[Server thread/INFO]: [BentoBox] Loading warps...
[Server thread/INFO]: [BentoBox] Enabling WelcomeWarps...-0.1.0-snapshot
[Server thread/INFO]: [BentoBox] Addons successfully enabled.
[Server thread/INFO]: [BentoBox] Added world SkyBlock (HARD)
[Server thread/INFO]: [BentoBox] Added world AcidIsland (HARD)
[Server thread/INFO]: [BentoBox] Hooking with Vault...
[Server thread/INFO]: [BentoBox] Hooking with PlaceholderAPI...
[Server thread/INFO]: [BentoBox] ##########################################
[Server thread/INFO]: [BentoBox] BentoBox v0.14.0-SNAPSHOT has been fully enabled.
[Server thread/INFO]: [BentoBox] It took: 11810ms
[Server thread/INFO]: [BentoBox] Thanks for using our plugin !
[Server thread/INFO]: [BentoBox] - Tastybento and Poslovitch, 2017-2018
[Server thread/INFO]: [BentoBox] #############################################

other plugin:
all essentials  2.15.0.52
multiversecore
logblock
FAWE
worldguard but i dont create a RG
Bungeetablistplus
Multichat
protocollib
vault
worldborder

**Comment by tastybento** [comment]
Currently, money rewards are not supported. A work around is to use reward commands to give money using a pay command or something like that.

**Comment by tastybento** [comment]
Done thanks to BONNe.
