### ISSUE TITLE
Case sensitive "LEVEL" 

### ISSUE THREAD

**Issue by robert-beckley** [BentoBoxWorld/addon-challenges#33]
Hey, I know Challenges Addon is due a rework but thought I would raise this now to get it in.

For the challange Type "Level" it appres to function on a case sensitive basis. The issue being that the case used in the default config is wrong.

I think a equalsIgnoreCase() would fix it

To reproduce just change the case around and restart the server.  

![image](https://user-images.githubusercontent.com/41904721/49324437-be793180-f581-11e8-8f61-4924bd9dda20.png)
![image](https://user-images.githubusercontent.com/41904721/49324441-c8029980-f581-11e8-9eef-ec29ef3fead8.png)
![image](https://user-images.githubusercontent.com/41904721/49324442-ce911100-f581-11e8-9975-777f6c37f086.png)

Thanks to @ShakeforProtein and @PhysicsProdigy for pointing this out.

**Comment by tastybento** [comment]
Thanks.

By the way, watch out because a recent commit to BentoBox (18 hours ago) caused a lot of enums like this to be corrupted to their default value when loading the file. You may need to revert to backups of the files.
