### ISSUE TITLE
default challange file

### ISSUE THREAD

**Issue by Scorpionvssub** [BentoBoxWorld/addon-challenges#35]
Loading up challenges along side level addon and everything else seems to not be read, keeps saying no challenges loaded - contact an admin while...its a default config?

Edit: Seems ya still need to do /bsb challenge cimport

**Comment by tastybento** [comment]
Yes, instructions have been added to the develop branch. I'm going to merger into the master branch so it's more on the front page.

https://github.com/BentoBoxWorld/addon-challenges/tree/develop
