### ISSUE TITLE
/is challenges not working

### ISSUE THREAD

**Issue by Zenya4** [BentoBoxWorld/addon-challenges#37]
Using default config and challenges, I get this when I type `/is challenges`

`That command is not ready yet - contact admin` (Ingame)
`[15:24:34 ERROR]: [BentoBox] There are no challenges set up!` (Console)

Using:
BentoBox 0.16.0
BSkyBlock 0.5.0
addon-challenges: 0.3.0

**Comment by Zenya4** [comment]
Nevermind, I just forgot to use `/bsb challenges import`. I'll just leave this here for future reference. Perhaps a config option to make it automatically import challenges should be implemented

**Comment by tastybento** [comment]
It’s in the instructions. 

The import function is meant to assist with askyblock transition and ultimately was not planned to be the normal way to add challenges. The add on is just not finished yet so that why.

**Comment by tastybento** [comment]
Pinned so others can see it.
