### ISSUE TITLE
Spezial enchanted items in challenges

### ISSUE THREAD

**Issue by Max2124** [BentoBoxWorld/addon-challenges#5]
I don't know if it's possible yet but i wanted to give players spezial enchanted items wich where enchanted by annother plugin.
So here would be my solutionfor that:
A command (something like: “/bsadmin item add [spezial item id]“ to creat an spezial id for this item and to remove this id the command: “/bsadmin item delete [spezial item id]“ and the command like: “/bsadmin item list“ to see a list in chat of all already given spezial Item IDs.
Because i don't know how to do that.

**Comment by tastybento** [comment]
You can use challenge reward commands to give players items if it is possible to use a command to do so.

**Comment by Max2124** [comment]
Ok, well I meant like the name/description and enchantment not like normal
items(durability 10 and name "&2Spezial Item"). But anyway thanks for the
message tastybento. :)
