### ISSUE TITLE
"Surrounding" type challenges not working

### ISSUE THREAD

**Issue by FortyEffs** [BentoBoxWorld/addon-challenges#8]
These challenges import as "Island" type, which gives the error: https://pastebin.com/T5QTDhuX, when I try to complete one.

Changing the type to surrounding in the challenge file causes the plugin to stop working completely

**Comment by tastybento** [comment]
I’ll look into it. I’m in China this week so please wait.

**Comment by tastybento** [comment]
Fixed in the commit.
